# Generated by Django 5.2.6 on 2025-11-09 05:12

import django.db.models.deletion
import system.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('id', models.CharField(default=system.models.generate_employee_id, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('reviewed_by_rm', models.BooleanField(default=False)),
                ('reviewed_by_hr', models.BooleanField(default=False)),
                ('reviewed_by_hod', models.BooleanField(default=False)),
                ('reviewed_by_coo', models.BooleanField(default=False)),
                ('reviewed_by_ceo', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BdDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'BD District',
                'verbose_name_plural': 'BD Districts',
            },
        ),
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True)),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Blood Group',
                'verbose_name_plural': 'Blood Groups',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Degree',
                'verbose_name_plural': 'Degrees',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContactRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Emergency Contact Relationship',
                'verbose_name_plural': 'Emergency Contact Relationships',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Marital Status',
                'verbose_name_plural': 'Marital Statuses',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
            },
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'TrainingType',
                'verbose_name_plural': 'TrainingTypes',
            },
        ),
        migrations.CreateModel(
            name='Ceo',
            fields=[
                ('ceo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='as_ceo', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coo',
            fields=[
                ('coo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='as_coo', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('hod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='as_hod', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('hr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='as_hr', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingManager',
            fields=[
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='as_manager', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='system.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='system.designation'),
        ),
        migrations.AddField(
            model_name='designation',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designation', to='system.grade'),
        ),
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='system.grade'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='system.role'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace', models.CharField(choices=[('MyProfile', 'MyProfile'), ('MyAppraisal', 'MyAppraisal'), ('ReviewAppraisal', 'ReviewAppraisal'), ('AllAppraisal', 'AllAppraisal'), ('Employee', 'Employee'), ('Configuration', 'Configuration')], max_length=50)),
                ('sub_workspace', models.CharField(choices=[('MyOfficialDetail', 'MyOfficialDetail'), ('MyPersonalDetail', 'MyPersonalDetail'), ('MyAddress', 'MyAddress'), ('MyWorkExperience', 'MyWorkExperience'), ('MyEducation', 'MyEducation'), ('MyTrainingCertificate', 'MyTrainingCertificate'), ('MyAttachment', 'MyAttachment'), ('EmployeeList', 'EmployeeList'), ('EmployeeOfficialDetail', 'EmployeeOfficialDetail'), ('EmployeePersonalDetail', 'EmployeePersonalDetail'), ('EmployeeAddress', 'EmployeeAddress'), ('EmployeeWorkExperience', 'EmployeeWorkExperience'), ('EmployeeEducation', 'EmployeeEducation'), ('EmployeeTrainingCertificate', 'EmployeeTrainingCertificate'), ('EmployeeAttachment', 'EmployeeAttachment'), ('MyAppraisalDetail', 'MyAppraisalDetail'), ('MyEmployeeAppraisal', 'MyEmployeeAppraisal'), ('MyRmReview', 'MyRmReview'), ('MyHrReview', 'MyHrReview'), ('MyHodReview', 'MyHodReview'), ('MyCooReview', 'MyCooReview'), ('MyCeoReview', 'MyCeoReview'), ('ReviewAppraisalList', 'ReviewAppraisalList'), ('EmployeeAppraisalDetail', 'EmployeeAppraisalDetail'), ('EmployeeEmployeeAppraisal', 'EmployeeEmployeeAppraisal'), ('EmployeeRmReview', 'EmployeeRmReview'), ('EmployeeHrReview', 'EmployeeHrReview'), ('EmployeeHodReview', 'EmployeeHodReview'), ('EmployeeCooReview', 'EmployeeCooReview'), ('EmployeeCeoReview', 'EmployeeCeoReview'), ('AppraisalStatus', 'AppraisalStatus'), ('AllAppraisalList', 'AllAppraisalList'), ('AllAppraisalDetail', 'AllAppraisalDetail'), ('AllEmployeeAppraisal', 'AllEmployeeAppraisal'), ('AllRmReview', 'AllRmReview'), ('AllHrReview', 'AllHrReview'), ('AllHodReview', 'AllHodReview'), ('AllCooReview', 'AllCooReview'), ('AllCeoReview', 'AllCeoReview'), ('Department', 'Department'), ('Designation', 'Designation'), ('Grade', 'Grade'), ('Role', 'Role')], max_length=50)),
                ('view', models.BooleanField(default=False)),
                ('create', models.BooleanField(default=False)),
                ('edit', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('download', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='system.role')),
            ],
            options={
                'verbose_name': 'System Role Permission',
                'verbose_name_plural': 'System Role Permissions',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='system.reportingmanager'),
        ),
        migrations.CreateModel(
            name='BdThana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanas', to='system.bddistrict')),
            ],
            options={
                'verbose_name': 'BD Thana',
                'verbose_name_plural': 'BD Thanas',
                'unique_together': {('name', 'district')},
            },
        ),
    ]
