# Generated by Django 5.2.6 on 2025-09-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
