# Generated by Django 5.2.6 on 2025-10-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
