# Generated by Django 5.2.6 on 2025-11-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='basic_salary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
