# Generated by Django 5.2.6 on 2025-10-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='active',
            new_name='status',
        ),
    ]
