# Generated by Django 5.2.6 on 2025-09-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('casual_leave_taken', models.IntegerField(default=0)),
                ('sick_leave_taken', models.IntegerField(default=0)),
                ('earned_leave_taken', models.IntegerField(default=0)),
                ('total_leave_taken', models.IntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('attendance_rating', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAppraisal',
            fields=[
                ('appraisal_id', models.AutoField(primary_key=True, serialize=False)),
                ('appraisal_submitted_date', models.DateField(auto_now_add=True)),
                ('achievements', models.TextField(max_length=1000)),
                ('strengths', models.TextField(max_length=1000)),
                ('improvements', models.TextField(max_length=1000)),
                ('training_needs', models.TextField(max_length=500)),
                ('soft_skills_training', models.BooleanField(default=False)),
                ('business_training', models.BooleanField(default=False)),
                ('technical_training', models.BooleanField(default=False)),
                ('is_review_period_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAppraisalTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_self_appraisal_start', models.DateField(blank=True, null=True)),
                ('employee_self_appraisal_end', models.DateField(blank=True, null=True)),
                ('employee_self_appraisal_remind', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Employee Appraisal Timers',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAppraisalTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('self_appraisal_done', models.CharField(default='NA', max_length=10)),
                ('rm_review_done', models.CharField(default='NA', max_length=10)),
                ('hr_review_done', models.CharField(default='NA', max_length=10)),
                ('hod_review_done', models.CharField(default='NA', max_length=10)),
                ('coo_review_done', models.CharField(default='NA', max_length=10)),
                ('ceo_review_done', models.CharField(default='NA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FinalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_role', models.CharField(choices=[('hod', 'HOD'), ('coo', 'COO'), ('ceo', 'CEO')], max_length=10)),
                ('agreement_remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('decision_remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('decision', models.CharField(blank=True, choices=[('Promotion with Increment', 'Promotion Recommended with Increment'), ('Promotion with PP only', 'Promotion Recommended with PP only'), ('Increment without Promotion', 'Increment Recommended without Promotion'), ('Only Pay Progression (PP) Recommended', 'Only Pay Progression (PP) Recommended'), ('Promotion/Increment/PP Deferred', 'Promotion/Increment/PP Deferred')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FinalReviewerAppraisalTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_review_start', models.DateField(blank=True, null=True)),
                ('final_review_end', models.DateField(blank=True, null=True)),
                ('final_review_remind', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Final Reviewer Appraisal Timers',
            },
        ),
        migrations.CreateModel(
            name='HRReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('promotion_recommended_with_increment', models.BooleanField(default=False)),
                ('promotion_recommended_with_pp', models.BooleanField(default=False)),
                ('increment_recommended', models.BooleanField(default=False)),
                ('pay_progression_recommended', models.BooleanField(default=False)),
                ('promotion_increment_pp_deferred', models.BooleanField(default=False)),
                ('decision_remarks', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingManagerAppraisalTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_manager_review_start', models.DateField(blank=True, null=True)),
                ('reporting_manager_review_end', models.DateField(blank=True, null=True)),
                ('reporting_manager_review_remind', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '2. Reporting Manager Appraisal Timers',
            },
        ),
        migrations.CreateModel(
            name='ReportingManagerAppraisalTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'All Reviews Submitted')], default='not_started', max_length=20)),
                ('progress_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportingManagerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements_remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('training_remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('justify_overall_rating', models.TextField(blank=True, max_length=1000, null=True)),
                ('overall_performance_rating', models.CharField(blank=True, choices=[('does_not_meet', 'Does not meet expectation'), ('partially_meets', 'Partially meets expectation'), ('meets_expectation', 'Meets expectation'), ('meets_most_expectation', 'Meets most expectation'), ('exceeds_expectation', 'Exceeds Expectation')], max_length=50, null=True)),
                ('potential_rating', models.CharField(blank=True, choices=[('low_potential', 'Low Potential'), ('medium_potential', 'Medium potential'), ('high_potential', 'High potential')], max_length=50, null=True)),
                ('decision_remarks', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryVariance',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_basic', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('proposed_basic', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proposed_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('Promotion with Increment', 'Promotion Recommended with Increment'), ('Promotion with PP only', 'Promotion Recommended with PP only'), ('Increment without Promotion', 'Increment Recommended without Promotion'), ('Only Pay Progression (PP) Recommended', 'Only Pay Progression (PP) Recommended'), ('Promotion/Increment/PP Deferred', 'Promotion/Increment/PP Deferred')], max_length=100)),
            ],
        ),
    ]
