# Generated by Django 5.2.6 on 2025-11-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appraisal_start_date', models.DateField(blank=True, null=True, verbose_name='Appraisal Start Date')),
                ('appraisal_end_date', models.DateField(blank=True, null=True, verbose_name='Appraisal End Date')),
                ('factor', models.DecimalField(decimal_places=2, default=0.55, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AppraisalDetailsBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appraisal_start_date', models.DateField(blank=True, null=True, verbose_name='Appraisal Start Date')),
                ('appraisal_end_date', models.DateField(blank=True, null=True, verbose_name='Appraisal End Date')),
                ('factor', models.DecimalField(decimal_places=2, default=0.55, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Appraisal Backups',
            },
        ),
        migrations.CreateModel(
            name='CeoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(max_length=1000, verbose_name='General Remarks (CEO)')),
                ('promo_w_increment', models.BooleanField(default=False, verbose_name='Promo with Increment')),
                ('promo_w_increment_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('promo_w_pp', models.BooleanField(default=False, verbose_name='Promotion Recommended with PP only')),
                ('promo_w_pp_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('increment_w_no_promo', models.BooleanField(default=False, verbose_name='Increment w/o Promo')),
                ('increment_w_no_promo_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('pp_only', models.BooleanField(default=False, verbose_name='PP Only')),
                ('pp_only_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('deferred', models.BooleanField(default=False, verbose_name='Deferred')),
                ('deferred_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('remarks_on_your_decision', models.TextField(blank=True, max_length=500, null=True, verbose_name='Final Decision Remarks (CEO)')),
            ],
        ),
        migrations.CreateModel(
            name='CooReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(max_length=1000, verbose_name='General Remarks (COO)')),
                ('promo_w_increment', models.BooleanField(default=False, verbose_name='Promo with Increment')),
                ('promo_w_increment_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('promo_w_pp', models.BooleanField(default=False, verbose_name='Promotion Recommended with PP only')),
                ('promo_w_pp_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('increment_w_no_promo', models.BooleanField(default=False, verbose_name='Increment w/o Promo')),
                ('increment_w_no_promo_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('pp_only', models.BooleanField(default=False, verbose_name='PP Only')),
                ('pp_only_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('deferred', models.BooleanField(default=False, verbose_name='Deferred')),
                ('deferred_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('remarks_on_your_decision', models.TextField(blank=True, max_length=500, null=True, verbose_name='Final Decision Remarks (COO)')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievements_goal_completion', models.TextField(max_length=1000)),
                ('training_plan', models.TextField(max_length=1000)),
                ('development_plan', models.TextField(max_length=1000)),
                ('soft_skills_training', models.BooleanField(default=False)),
                ('business_training', models.BooleanField(default=False)),
                ('technical_training', models.BooleanField(default=False)),
                ('training_description', models.TextField(max_length=500)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAppraisalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appraisal_date', models.DateTimeField(blank=True, null=True)),
                ('self_appraisal_done', models.CharField(blank=True, choices=[('NA', 'NA'), ('PENDING', 'PENDING'), ('DONE', 'DONE')], default='PENDING', max_length=10, null=True)),
                ('rm_review_done', models.CharField(blank=True, choices=[('NA', 'NA'), ('PENDING', 'PENDING'), ('DONE', 'DONE')], default='NA', max_length=10, null=True)),
                ('hr_review_done', models.CharField(blank=True, choices=[('NA', 'NA'), ('PENDING', 'PENDING'), ('DONE', 'DONE')], default='NA', max_length=10, null=True)),
                ('hod_review_done', models.CharField(blank=True, choices=[('NA', 'NA'), ('PENDING', 'PENDING'), ('DONE', 'DONE')], default='NA', max_length=10, null=True)),
                ('coo_review_done', models.CharField(blank=True, choices=[('NA', 'NA'), ('PENDING', 'PENDING'), ('DONE', 'DONE')], default='NA', max_length=10, null=True)),
                ('ceo_review_done', models.CharField(blank=True, choices=[('NA', 'NA'), ('PENDING', 'PENDING'), ('DONE', 'DONE')], default='NA', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAppraisalTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_self_appraisal_start', models.DateField(blank=True, null=True)),
                ('employee_self_appraisal_end', models.DateField(blank=True, null=True)),
                ('employee_self_appraisal_remind', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Employee Appraisal Timers',
            },
        ),
        migrations.CreateModel(
            name='HodReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(max_length=1000, verbose_name='General Remarks (HOD)')),
                ('promo_w_increment', models.BooleanField(default=False, verbose_name='Promo with Increment')),
                ('promo_w_increment_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('promo_w_pp', models.BooleanField(default=False, verbose_name='Promotion Recommended with PP only')),
                ('promo_w_pp_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('increment_w_no_promo', models.BooleanField(default=False, verbose_name='Increment w/o Promo')),
                ('increment_w_no_promo_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('pp_only', models.BooleanField(default=False, verbose_name='PP Only')),
                ('pp_only_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('deferred', models.BooleanField(default=False, verbose_name='Deferred')),
                ('deferred_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('remarks_on_your_decision', models.TextField(blank=True, max_length=500, null=True, verbose_name='Final Decision Remarks (HOD)')),
            ],
        ),
        migrations.CreateModel(
            name='HrReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks_hr', models.TextField(max_length=1000, verbose_name='Remarks from Human Resource')),
                ('casual_leave_taken', models.IntegerField(default=0, verbose_name='Casual Leave Taken')),
                ('sick_leave_taken', models.IntegerField(default=0, verbose_name='Sick Leave Taken')),
                ('annual_leave_taken', models.IntegerField(default=0, verbose_name='Annual Leave Taken')),
                ('on_time_count', models.IntegerField(default=0, verbose_name='On Time Count')),
                ('delay_count', models.IntegerField(default=0, verbose_name='Delay Count')),
                ('early_exit_count', models.IntegerField(default=0, verbose_name='Early Exit Count')),
                ('current_basic', models.IntegerField(default=0)),
                ('promo_with_increment_proposed_basic', models.IntegerField(default=0)),
                ('promo_without_increment_proposed_basic', models.IntegerField(default=0)),
                ('increment_proposed_basic', models.IntegerField(default=0)),
                ('pp_proposed_basic', models.IntegerField(default=0)),
                ('promo_w_increment', models.BooleanField(default=False, verbose_name='Promo with Increment')),
                ('promo_w_increment_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('promo_w_pp', models.BooleanField(default=False, verbose_name='Promotion Recommended with PP only')),
                ('promo_w_pp_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('increment_w_no_promo', models.BooleanField(default=False, verbose_name='Increment w/o Promo')),
                ('increment_w_no_promo_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('pp_only', models.BooleanField(default=False, verbose_name='PP Only')),
                ('pp_only_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('deferred', models.BooleanField(default=False, verbose_name='Deferred')),
                ('deferred_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('remarks_on_your_decision', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingManagerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements_remarks', models.TextField(max_length=500, verbose_name='Achievements/Goal Completion Remarks')),
                ('training_remarks', models.TextField(max_length=500, verbose_name='Training and Development Plan Remarks')),
                ('overall_performance_rating', models.CharField(choices=[('does_not_meet', 'Does not meet expectation'), ('partially_meets', 'Partially meets expectation'), ('meets_expectation', 'Meets expectation'), ('meets_most_expectation', 'Meets most expectation'), ('exceeds_expectation', 'Exceeds Expectation')], max_length=50, verbose_name='Overall Performance Rating')),
                ('justify_overall_rating', models.TextField(max_length=500, verbose_name='Justification for Overall Rating')),
                ('potential_rating', models.CharField(choices=[('low_potential', 'Low Potential'), ('medium_potential', 'Medium potential'), ('high_potential', 'High potential')], max_length=50, verbose_name='Potential Rating')),
                ('decision_remarks', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Final Remarks on Decision/Potential')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
