# Generated by Django 5.2.6 on 2025-09-11 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('casual_leave_taken', models.IntegerField(default=0)),
                ('sick_leave_taken', models.IntegerField(default=0)),
                ('earned_leave_taken', models.IntegerField(default=0)),
                ('total_leave_taken', models.IntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('attendance_rating', models.CharField(blank=True, max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_summaries', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAppraisal',
            fields=[
                ('appraisal_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_period_start', models.DateField()),
                ('review_period_end', models.DateField()),
                ('achievements', models.TextField(max_length=1000)),
                ('strengths', models.TextField(max_length=1000)),
                ('improvements', models.TextField(max_length=1000)),
                ('training_needs', models.TextField(max_length=500)),
                ('soft_skills_training', models.BooleanField(default=False)),
                ('business_training', models.BooleanField(default=False)),
                ('technical_training', models.BooleanField(default=False)),
                ('is_review_period_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='self_appraisals', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FinalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_role', models.CharField(choices=[('hod', 'HOD'), ('coo', 'COO'), ('ceo', 'CEO')], max_length=10)),
                ('agreement_remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('decision_remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('promotion_recommended_with_increment', models.BooleanField(default=False)),
                ('promotion_recommended_with_pp', models.BooleanField(default=False)),
                ('increment_recommended', models.BooleanField(default=False)),
                ('pay_progression_recommended', models.BooleanField(default=False)),
                ('promotion_increment_pp_deferred', models.BooleanField(default=False)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_reviews', to='appraisals.employeeappraisal')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_review_appraisals', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ReportingManagerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements_remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('training_remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('justify_overall_rating', models.TextField(blank=True, max_length=1000, null=True)),
                ('overall_performance_rating', models.CharField(blank=True, choices=[('does_not_meet', 'Does not meet expectation'), ('partially_meets', 'Partially meets expectation'), ('meets_expectation', 'Meets expectation'), ('meets_most_expectation', 'Meets most expectation'), ('exceeds_expectation', 'Exceeds Expectation')], max_length=50, null=True)),
                ('potential_rating', models.CharField(blank=True, choices=[('low_potential', 'Low Potential'), ('medium_potential', 'Medium potential'), ('high_potential', 'High potential')], max_length=50, null=True)),
                ('decision_remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('appraisal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='manager_review', to='appraisals.employeeappraisal')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_appraisals', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryVariance',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_basic', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('proposed_basic', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proposed_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('Promotion with Increment', 'Promotion Recommended with Increment'), ('Promotion with PP only', 'Promotion Recommended with PP only'), ('Increment without Promotion', 'Increment Recommended without Promotion'), ('Only Pay Progression (PP) Recommended', 'Only Pay Progression (PP) Recommended'), ('Promotion/Increment/PP Deferred', 'Promotion/Increment/PP Deferred')], max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_recommendations', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='HRReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('promotion_recommended_with_increment', models.BooleanField(default=False)),
                ('promotion_recommended_with_pp', models.BooleanField(default=False)),
                ('increment_recommended', models.BooleanField(default=False)),
                ('pay_progression_recommended', models.BooleanField(default=False)),
                ('promotion_increment_pp_deferred', models.BooleanField(default=False)),
                ('decision_remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('appraisal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hr_review', to='appraisals.employeeappraisal')),
                ('attendance_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviews', to='appraisals.attendancesummary')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hr_appraisals', to='employees.employee')),
                ('salary_recommendation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviews', to='appraisals.salaryvariance')),
            ],
        ),
    ]
