# Generated by Django 5.2.6 on 2025-10-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeappraisalstatustrack',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='employeeappraisalstatustrack',
            name='last_archived_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
