# Generated by Django 5.2.6 on 2025-11-24 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appraisals', '0001_initial'),
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisaldetails',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisaldetails',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_appraisal_details', to='system.reportingmanager'),
        ),
        migrations.AddField(
            model_name='appraisaldetailsbackup',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_details_backups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisaldetailsbackup',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_appraisal_details_backups', to='system.reportingmanager'),
        ),
        migrations.AddField(
            model_name='appraisaldetailsbackup',
            name='ceo_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_appraisal_detail', to='appraisals.ceoreview'),
        ),
        migrations.AddField(
            model_name='appraisaldetails',
            name='ceo_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_detail', to='appraisals.ceoreview'),
        ),
        migrations.AddField(
            model_name='appraisaldetailsbackup',
            name='coo_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_appraisal_detail', to='appraisals.cooreview'),
        ),
        migrations.AddField(
            model_name='appraisaldetails',
            name='coo_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_detail', to='appraisals.cooreview'),
        ),
        migrations.AddField(
            model_name='employeeappraisal',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_appraisals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cooreview',
            name='appraisal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coo_review', to='appraisals.employeeappraisal', verbose_name='Employee Appraisal'),
        ),
        migrations.AddField(
            model_name='ceoreview',
            name='appraisal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ceo_review', to='appraisals.employeeappraisal', verbose_name='Employee Appraisal'),
        ),
        migrations.AddField(
            model_name='appraisaldetailsbackup',
            name='emp_appraisal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_appraisal_detail', to='appraisals.employeeappraisal'),
        ),
        migrations.AddField(
            model_name='appraisaldetails',
            name='emp_appraisal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_detail', to='appraisals.employeeappraisal'),
        ),
        migrations.AddField(
            model_name='employeeappraisalstatus',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_appraisal_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisaldetails',
            name='appraisal_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_detail', to='appraisals.employeeappraisalstatus'),
        ),
        migrations.AddField(
            model_name='employeeappraisaltimer',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_timers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hodreview',
            name='appraisal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hod_review', to='appraisals.employeeappraisal'),
        ),
        migrations.AddField(
            model_name='appraisaldetailsbackup',
            name='hod_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_appraisal_detail', to='appraisals.hodreview'),
        ),
        migrations.AddField(
            model_name='appraisaldetails',
            name='hod_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_detail', to='appraisals.hodreview'),
        ),
        migrations.AddField(
            model_name='hrreview',
            name='appraisal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_review', to='appraisals.employeeappraisal'),
        ),
        migrations.AddField(
            model_name='appraisaldetailsbackup',
            name='hr_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_appraisal_detail', to='appraisals.hrreview'),
        ),
        migrations.AddField(
            model_name='appraisaldetails',
            name='hr_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_detail', to='appraisals.hrreview'),
        ),
        migrations.AddField(
            model_name='reportingmanagerreview',
            name='appraisal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rm_review', to='appraisals.employeeappraisal'),
        ),
        migrations.AddField(
            model_name='appraisaldetailsbackup',
            name='rm_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_appraisal_detail', to='appraisals.reportingmanagerreview'),
        ),
        migrations.AddField(
            model_name='appraisaldetails',
            name='rm_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_detail', to='appraisals.reportingmanagerreview'),
        ),
    ]
