# Generated by Django 5.2.6 on 2025-09-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalreview',
            name='increment_recommended',
        ),
        migrations.RemoveField(
            model_name='finalreview',
            name='pay_progression_recommended',
        ),
        migrations.RemoveField(
            model_name='finalreview',
            name='promotion_increment_pp_deferred',
        ),
        migrations.RemoveField(
            model_name='finalreview',
            name='promotion_recommended_with_increment',
        ),
        migrations.RemoveField(
            model_name='finalreview',
            name='promotion_recommended_with_pp',
        ),
        migrations.AddField(
            model_name='finalreview',
            name='decision',
            field=models.CharField(blank=True, choices=[('Promotion with Increment', 'Promotion Recommended with Increment'), ('Promotion with PP only', 'Promotion Recommended with PP only'), ('Increment without Promotion', 'Increment Recommended without Promotion'), ('Only Pay Progression (PP) Recommended', 'Only Pay Progression (PP) Recommended'), ('Promotion/Increment/PP Deferred', 'Promotion/Increment/PP Deferred')], max_length=100),
        ),
    ]
