# Generated by Django 5.2.6 on 2025-09-16 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0001_initial'),
        ('employees', '0002_reportingmanager_alter_employee_reporting_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAppraisalTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('self', 'Self-Appraisal Submitted'), ('rm', 'Reporting Manager Reviewed'), ('hr', 'HR Reviewed'), ('hod', 'HOD Reviewed'), ('coo', 'COO Reviewed'), ('ceo', 'CEO Reviewed'), ('completed', 'Process Completed')], default='self', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinalReviewerAppraisalTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_review_start', models.DateField(blank=True, null=True)),
                ('final_review_end', models.DateField(blank=True, null=True)),
                ('final_review_remind', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Reviewer Appraisal Timers',
            },
        ),
        migrations.CreateModel(
            name='ReportingManagerAppraisalTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'All Reviews Submitted')], default='not_started', max_length=20)),
                ('progress_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='ReviewerAppraisalTimer',
        ),
        migrations.AlterModelOptions(
            name='employeeappraisaltimer',
            options={'verbose_name_plural': 'Employee Appraisal Timers'},
        ),
        migrations.AlterModelOptions(
            name='reportingmanagerappraisaltimer',
            options={'verbose_name_plural': 'Reporting Manager Appraisal Timers'},
        ),
        migrations.RenameField(
            model_name='employeeappraisaltimer',
            old_name='employee_appraisal_end',
            new_name='employee_self_appraisal_end',
        ),
        migrations.RenameField(
            model_name='employeeappraisaltimer',
            old_name='employee_appraisal_remind',
            new_name='employee_self_appraisal_remind',
        ),
        migrations.RenameField(
            model_name='employeeappraisaltimer',
            old_name='employee_appraisal_start',
            new_name='employee_self_appraisal_start',
        ),
        migrations.AddField(
            model_name='employeeappraisaltrack',
            name='appraisal_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_tracks', to='appraisals.employeeappraisaltimer'),
        ),
        migrations.AddField(
            model_name='employeeappraisaltrack',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_track', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='reportingmanagerappraisaltrack',
            name='appraisal_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_tracks', to='appraisals.reportingmanagerappraisaltimer'),
        ),
        migrations.AddField(
            model_name='reportingmanagerappraisaltrack',
            name='reporting_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_appraisal_tracks', to='employees.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='reportingmanagerappraisaltrack',
            unique_together={('reporting_manager', 'appraisal_cycle')},
        ),
    ]
