# Generated by Django 5.2.6 on 2025-09-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appraisaltimer',
            options={'verbose_name_plural': 'Appraisal Timer'},
        ),
        migrations.AddField(
            model_name='employeeappraisal',
            name='appraisal_date',
            field=models.DateField(auto_now_add=True, default='2025-09-11'),
            preserve_default=False,
        ),
    ]
