# Generated by Django 5.2.6 on 2025-10-15 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appraisals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesummary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ceoreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ceo_appraisals', to=settings.AUTH_USER_MODEL, verbose_name='CEO Reviewer'),
        ),
        migrations.AddField(
            model_name='cooreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coo_appraisals', to=settings.AUTH_USER_MODEL, verbose_name='COO Reviewer'),
        ),
        migrations.AddField(
            model_name='employeeappraisal',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='self_appraisals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cooreview',
            name='appraisal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coo_review', to='appraisals.employeeappraisal', verbose_name='Employee Appraisal'),
        ),
        migrations.AddField(
            model_name='ceoreview',
            name='appraisal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ceo_review', to='appraisals.employeeappraisal', verbose_name='Employee Appraisal'),
        ),
        migrations.AddField(
            model_name='employeeappraisalstatustrack',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_track', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeappraisaltimer',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hodreview',
            name='appraisal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hod_review', to='appraisals.employeeappraisal', verbose_name='Employee Appraisal'),
        ),
        migrations.AddField(
            model_name='hodreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hod_appraisals', to=settings.AUTH_USER_MODEL, verbose_name='HOD Reviewer'),
        ),
        migrations.AddField(
            model_name='hrreview',
            name='appraisal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hr_review', to='appraisals.employeeappraisal'),
        ),
        migrations.AddField(
            model_name='hrreview',
            name='attendance_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviews', to='appraisals.attendancesummary'),
        ),
        migrations.AddField(
            model_name='hrreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hr_appraisals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportingmanagerappraisaltrack',
            name='appraisal_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_tracks', to='appraisals.reportingmanagerappraisaltimer'),
        ),
        migrations.AddField(
            model_name='reportingmanagerappraisaltrack',
            name='reporting_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_appraisal_tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportingmanagerreview',
            name='appraisal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='manager_review', to='appraisals.employeeappraisal', verbose_name='Employee Appraisal'),
        ),
        migrations.AddField(
            model_name='reportingmanagerreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_appraisals', to=settings.AUTH_USER_MODEL, verbose_name='Reporting Manager'),
        ),
        migrations.AddField(
            model_name='salaryrecommendation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hrreview',
            name='salary_recommendation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviews', to='appraisals.salaryrecommendation'),
        ),
        migrations.AlterUniqueTogether(
            name='reportingmanagerappraisaltrack',
            unique_together={('reporting_manager', 'appraisal_cycle')},
        ),
    ]
