# Generated by Django 5.2.6 on 2025-09-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisaltimer',
            old_name='remind_date',
            new_name='employee_appraisal_end',
        ),
        migrations.AddField(
            model_name='appraisaltimer',
            name='employee_appraisal_remind',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisaltimer',
            name='employee_appraisal_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisaltimer',
            name='review_period_remind',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisaltimer',
            name='review_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisaltimer',
            name='review_period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
