# Generated by Django 5.2.6 on 2025-11-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeappraisalstatus',
            name='appraisal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
