# Generated by Django 5.2.6 on 2025-09-14 11:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period_start', models.DateField()),
                ('review_period_end', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Appraisal Timer',
            },
        ),
        migrations.RemoveField(
            model_name='employeeappraisal',
            name='review_period_end',
        ),
        migrations.RemoveField(
            model_name='employeeappraisal',
            name='review_period_start',
        ),
        migrations.AddField(
            model_name='employeeappraisal',
            name='appraisal_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeappraisal',
            name='appraisal_period',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='appraisals', to='appraisals.appraisaltimer'),
        ),
    ]
