# Generated by Django 5.2.6 on 2025-09-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0002_rename_remind_date_appraisaltimer_employee_appraisal_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAppraisalTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_appraisal_start', models.DateField(blank=True, null=True)),
                ('employee_appraisal_end', models.DateField(blank=True, null=True)),
                ('employee_appraisal_remind', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Employee Appraisal Timers',
            },
        ),
        migrations.CreateModel(
            name='ReportingManagerAppraisalTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period_start', models.DateField(blank=True, null=True)),
                ('review_period_end', models.DateField(blank=True, null=True)),
                ('review_period_remind', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Reporting Manager Appraisal Timer',
            },
        ),
        migrations.DeleteModel(
            name='AppraisalTimer',
        ),
    ]
