# Generated by Django 5.2.6 on 2025-09-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0002_employeeappraisaltrack_finalreviewerappraisaltimer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalreviewerappraisaltimer',
            options={'verbose_name_plural': 'Final Reviewer Appraisal Timers'},
        ),
    ]
