# Generated by Django 5.2.6 on 2025-11-10 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0003_alter_employeeappraisalstatus_appraisal_date'),
        ('system', '0002_alter_employee_basic_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisaldetails',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_appraisal_details', to='system.reportingmanager'),
        ),
        migrations.AlterField(
            model_name='appraisaldetailsbackup',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_appraisal_details_backups', to='system.reportingmanager'),
        ),
    ]
