# Generated by Django 5.2.6 on 2025-09-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0003_employeeappraisaltimer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerAppraisalTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_period_start', models.DateField(blank=True, null=True)),
                ('reviewer_period_end', models.DateField(blank=True, null=True)),
                ('reviewer_period_remind', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Reviewer Appraisal Timer',
            },
        ),
        migrations.AlterModelOptions(
            name='employeeappraisaltimer',
            options={'verbose_name_plural': 'Employee Appraisal Timer'},
        ),
        migrations.RenameField(
            model_name='reportingmanagerappraisaltimer',
            old_name='review_period_end',
            new_name='reporting_manager_review_end',
        ),
        migrations.RenameField(
            model_name='reportingmanagerappraisaltimer',
            old_name='review_period_remind',
            new_name='reporting_manager_review_remind',
        ),
        migrations.RemoveField(
            model_name='reportingmanagerappraisaltimer',
            name='review_period_start',
        ),
        migrations.AddField(
            model_name='reportingmanagerappraisaltimer',
            name='reporting_manager_review_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
