# Generated by Django 5.2.6 on 2025-11-10 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0004_alter_appraisaldetails_reporting_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeappraisalstatus',
            name='appraisalDetails',
        ),
        migrations.AddField(
            model_name='appraisaldetails',
            name='appraisal_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_detail', to='appraisals.employeeappraisalstatus'),
        ),
    ]
