# Generated by Django 5.2.6 on 2025-10-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeattendance',
            old_name='outside_region_seconds',
            new_name='outside_region_time',
        ),
        migrations.RenameField(
            model_name='employeeattendance',
            old_name='total_work_seconds',
            new_name='total_work_time',
        ),
    ]
