# choices.py

BLOOD_GROUP_CHOICES = [
    ("A+", "A+"),
    ("A-", "A-"),
    ("B+", "B+"),
    ("B-", "B-"),
    ("AB+", "AB+"),
    ("AB-", "AB-"),
    ("O+", "O+"),
    ("O-", "O-"),
]

MARITAL_STATUS_CHOICES = [
    ("Single", "Single"),
    ("Married", "Married"),
    ("Divorced", "Divorced"),
    ("Widowed", "Widowed"),
]

DEGREE_CHOICES = [
    ("SSC", "Secondary School Certificate (SSC)"),
    ("HSC", "Higher Secondary Certificate (HSC)"),
    ("DIPLOMA", "Diploma"),
    ("BSC", "Bachelor of Science (B.Sc)"),
    ("BA", "Bachelor of Arts (B.A)"),
    ("BBA", "Bachelor of Business Administration (BBA)"),
    ("BSS", "Bachelor of Social Science (BSS)"),
    ("LLB", "Bachelor of Laws (LLB)"),
    ("MBBS", "Bachelor of Medicine, Bachelor of Surgery (MBBS)"),
    ("MSC", "Master of Science (M.Sc)"),
    ("MA", "Master of Arts (M.A)"),
    ("MBA", "Master of Business Administration (MBA)"),
    ("MSS", "Master of Social Science (MSS)"),
    ("LLM", "Master of Laws (LLM)"),
    ("MPhil", "Master of Philosophy (MPhil)"),
    ("PhD", "Doctor of Philosophy (PhD)"),
    ("POSTDOC", "Postdoctoral Research"),
]

SPECIALIZATION_CHOICES = [
    ("CSE", "Computer Science & Engineering"),
    ("EEE", "Electrical & Electronic Engineering"),
    ("CE", "Civil Engineering"),
    ("ME", "Mechanical Engineering"),
    ("IPE", "Industrial & Production Engineering"),
    ("BBA_FIN", "Business Administration - Finance"),
    ("BBA_MKT", "Business Administration - Marketing"),
    ("BBA_HR", "Business Administration - Human Resources"),
    ("BBA_ACC", "Business Administration - Accounting"),
    ("ECON", "Economics"),
    ("LAW", "Law"),
    ("ENG", "English"),
    ("BAN", "Bangla"),
    ("PHIL", "Philosophy"),
    ("HIS", "History"),
    ("SOC", "Sociology"),
    ("PSCI", "Political Science"),
    ("PHYS", "Physics"),
    ("CHEM", "Chemistry"),
    ("MATH", "Mathematics"),
    ("BIO", "Biology"),
    ("STAT", "Statistics"),
    ("MED", "Medicine"),
    ("PHARMA", "Pharmacy"),
    ("NURS", "Nursing"),
    ("ARCH", "Architecture"),
    ("FINEART", "Fine Arts"),
    ("EDU", "Education"),
]

DISTRICT_CHOICES = [
    ("Bagerhat", "Bagerhat"),
    ("Bandarban", "Bandarban"),
    ("Barguna", "Barguna"),
    ("Barishal", "Barishal"),
    ("Bhola", "Bhola"),
    ("Bogura", "Bogura"),
    ("Brahmanbaria", "Brahmanbaria"),
    ("Chandpur", "Chandpur"),
    ("Chattogram", "Chattogram"),
    ("Chuadanga", "Chuadanga"),
    ("Cox's Bazar", "Cox's Bazar"),
    ("Cumilla", "Cumilla"),
    ("Dhaka", "Dhaka"),
    ("Dinajpur", "Dinajpur"),
    ("Faridpur", "Faridpur"),
    ("Feni", "Feni"),
    ("Gaibandha", "Gaibandha"),
    ("Gazipur", "Gazipur"),
    ("Gopalganj", "Gopalganj"),
    ("Habiganj", "Habiganj"),
    ("Jamalpur", "Jamalpur"),
    ("Jashore", "Jashore"),
    ("Jhalokati", "Jhalokati"),
    ("Jhenaidah", "Jhenaidah"),
    ("Joypurhat", "Joypurhat"),
    ("Khagrachhari", "Khagrachhari"),
    ("Khulna", "Khulna"),
    ("Kishoreganj", "Kishoreganj"),
    ("Kurigram", "Kurigram"),
    ("Kushtia", "Kushtia"),
    ("Lakshmipur", "Lakshmipur"),
    ("Lalmonirhat", "Lalmonirhat"),
    ("Madaripur", "Madaripur"),
    ("Magura", "Magura"),
    ("Manikganj", "Manikganj"),
    ("Meherpur", "Meherpur"),
    ("Moulvibazar", "Moulvibazar"),
    ("Munshiganj", "Munshiganj"),
    ("Mymensingh", "Mymensingh"),
    ("Naogaon", "Naogaon"),
    ("Narail", "Narail"),
    ("Narayanganj", "Narayanganj"),
    ("Narsingdi", "Narsingdi"),
    ("Natore", "Natore"),
    ("Netrokona", "Netrokona"),
    ("Nilphamari", "Nilphamari"),
    ("Noakhali", "Noakhali"),
    ("Pabna", "Pabna"),
    ("Panchagarh", "Panchagarh"),
    ("Patuakhali", "Patuakhali"),
    ("Pirojpur", "Pirojpur"),
    ("Rajbari", "Rajbari"),
    ("Rajshahi", "Rajshahi"),
    ("Rangamati", "Rangamati"),
    ("Rangpur", "Rangpur"),
    ("Satkhira", "Satkhira"),
    ("Shariatpur", "Shariatpur"),
    ("Sherpur", "Sherpur"),
    ("Sirajganj", "Sirajganj"),
    ("Sunamganj", "Sunamganj"),
    ("Sylhet", "Sylhet"),
    ("Tangail", "Tangail"),
    ("Thakurgaon", "Thakurgaon"),
]


POLICE_STATION_CHOICES = [
    # Dhaka Range / Units Dhaka
    ('Savar Model', 'Savar Model, Dhaka'),
    ('Ashulia', 'Ashulia, Dhaka'),
    ('Dhamrai', 'Dhamrai, Dhaka'),
    ('Keraniganj Model', 'Keraniganj Model, Dhaka'),
    ('Dakhin Keraniganj', 'Dakhin Keraniganj, Dhaka'),
    ('Nawabgonj', 'Nawabgonj, Dhaka'),
    ('Dohar', 'Dohar, Dhaka'),
    
    # Chittagong Range
    # (these are upazila / station names; some might not be police station names exactly as labelled)
    ('Chittagong Kotwali', 'Kotwali, Chittagong'),
    ('Panchlaish', 'Panchlaish, Chittagong'),
    ('Double Mooring', 'Double Mooring, Chittagong'),
    # ... etc — full list of 16 needed
    
    # Sylhet Range
    ('Zakigonj', 'Zakigonj, Sylhet'),
    ('Kanaighat', 'Kanaighat, Sylhet'),
    ('Bianabazar', 'Bianabazar, Sylhet'),
    ('Jointiapur', 'Jointiapur, Sylhet'),
    ('Goinghat', 'Goinghat, Sylhet'),
    ('Companigonj', 'Companigonj, Sylhet'),
    ('Balagong', 'Balagong, Sylhet'),
    ('Osmaninagor', 'Osmaninagor, Sylhet'),
    ('Bishanath', 'Bishanath, Sylhet'),
    ('Golapgonj', 'Golapgonj, Sylhet'),
    # etc if there are more
    
    # Khulna Range
    ('Chuadanga Sadar', 'Chuadanga Sadar, Khulna'),
    ('Damurhuda', 'Damurhuda, Khulna'),
    ('Alamdanga', 'Alamdanga, Khulna'),
    ('Jibonnagar', 'Jibonnagar, Khulna'),
    
    # Rangpur Range
    ('Kotwali, Rangpur', 'Kotwali, Rangpur'),
    ('Taragonj', 'Taragonj, Rangpur'),
    ('Bodorgonj', 'Bodorgonj, Rangpur'),
    ('Gonagachora', 'Gonagachora, Rangpur'),
    ('Mithapokor', 'Mithapokor, Rangpur'),
    ('Pirojpur', 'Pirojpur, Rangpur'),
    ('Pirgacha', 'Pirgacha, Rangpur'),
    ('Kawnia', 'Kawnia, Rangpur'),
    
    # Barisal Range
    ('Bhola', 'Bhola, Barisal'),
    ('Doulatkhan', 'Doulatkhan, Barisal'),
    ('Tajumaddin', 'Tajumaddin, Barisal'),
    ('Borhanuddin', 'Borhanuddin, Barisal'),
    ('Lalmohon', 'Lalmohon, Barisal'),
    ('Charfashion', 'Charfashion, Barisal'),
    ('Shashibhushan', 'Shashibhushan, Barisal'),
    ('Dakshin Ayicha', 'Dakshin Ayicha, Barisal'),
    ('Monpura', 'Monpura, Barisal'),
    
    # Rajshahi Range
    ('Pabna', 'Pabna, Rajshahi'),
    ('Eshordi', 'Eshordi, Rajshahi'),
    ('Atghoria', 'Atghoria, Rajshahi'),
    ('Chatmohor', 'Chatmohor, Rajshahi'),
    ('Vhangura', 'Vhangura, Rajshahi'),
    # etc — up to 11 in the range
    
    # Mymensingh Range
    ('Kotwali, Mymensingh', 'Kotwali, Mymensingh'),
    ('Muktagacha', 'Muktagacha, Mymensingh'),
    ('Fulbaria', 'Fulbaria, Mymensingh'),
    ('Pagla', 'Pagla, Mymensingh'),
    ('Trishal', 'Trishal, Mymensingh'),
    ('Gouripur', 'Gouripur, Mymensingh'),
    ('Ishorgonj', 'Ishorgonj, Mymensingh'),
    ('Nandail', 'Nandail, Mymensingh'),
    ('Fulpur', 'Fulpur, Mymensingh'),
    ('Haluaghat', 'Haluaghat, Mymensingh'),
    # etc
]

