WORKSPACE_CHOICES = [
    ("MyProfile", "MyProfile"),
    ("MyAppraisal", "MyAppraisal"),
    ("ReviewAppraisal", "ReviewAppraisal"),
    ("AllAppraisal", "AllAppraisal"),
    ("Employee", "Employee"),
    ("Configuration", "Configuration"),
]

SUB_WORKSPACE_CHOICES = [
    ("MyOfficialDetail", "MyOfficialDetail"),
    ("MyPersonalDetail", "MyPersonalDetail"),
    ("MyAddress", "MyAddress"),
    ("MyWorkExperience", "MyWorkExperience"),
    ("MyEducation", "MyEducation"),
    ("MyProfessionalCertificate", "MyProfessionalCertificate"),
    ("MyAttatchment", "MyAttachment"),
    ("EmployeeList", "EmployeeList"),
    ("EmployeeOfficialDetail", "EmployeeOfficialDetail"),
    ("EmployeePersonalDetail", "EmployeePersonalDetail"),
    ("EmployeeAddress", "EmployeeAddress"),
    ("EmployeeWorkExperience", "EmployeeWorkExperience"),
    ("EmployeeEducation", "EmployeeEducation"),
    ("EmployeeProfessionalCertificate", "EmployeeProfessionalCertificate"),
    ("EmployeeAttachment", "EmployeeAttachment"),
    ("MyEmployeeAppraisal", "MyEmployeeAppraisal"),
    ("MyRmReview", "MyRmReview"),
    ("MyHrReview", "MyHrReview"),
    ("MyHodReview", "MyHodReview"),
    ("MyCooReview", "MyCooReview"),
    ("MyCeoReview", "MyCeoReview"),
    ("ReviewAppraisalList", "ReviewAppraisalList"),
    ("EmployeeEmployeeAppraisal", "EmployeeEmployeeAppraisal"),
    ("EmployeeRmReview", "EmployeeRmReview"),
    ("EmployeeHrReview", "EmployeeHrReview"),
    ("EmployeeHodReview", "EmployeeHodReview"),
    ("EmployeeCooReview", "EmployeeCooReview"),
    ("EmployeeCeoReview", "EmployeeCeoReview"),
    ("AppraisalStatus", "AppraisalStatus"),
    ("AllAppraisalList", "AllAppraisalList"),
    ("AllEmployeeAppraisal", "AllEmployeeAppraisal"),
    ("AllRmReview", "AllRmReview"),
    ("AllHrReview", "AllHrReview"),
    ("AllHodReview", "AllHodReview"),
    ("AllCooReview", "AllCooReview"),
    ("AllCeoReview", "AllCeoReview"),
    ("Department", "Department"),
    ("Designation", "Designation"),
    ("Grade", "Grade"),
    ("Role", "Role"),
]