from django.urls import path
from .views import (
    MyAppraisalDetailsAPIView,
    MyEmployeeAppraisalAPIView,
    MyRmReviewAPIView,
    MyHrReviewAPIView,
    MyHodReviewAPIView,
    MyCooReviewAPIView,
    MyCeoReviewAPIView,

    RmReviewAppraisalListAPIView,
    HrReviewAppraisalListAPIView,
    HodReviewAppraisalListAPIView,
    CooReviewAppraisalListAPIView,
    CeoReviewAppraisalListAPIView,
    ReviewAppraisalDetailsAPIView,
    ReviewEmployeeAppraisalAPIView,
    EmployeeRmReviewAPIView,
    EmployeeHrReviewAPIView,
    EmployeeHodReviewAPIView,
    EmployeeCooReviewAPIView,
    EmployeeCeoReviewAPIView,

    AllAppraisalListAPIView,
    AllAppraisalDetailsAPIView,
    AllEmployeeAppraisalAPIView,
    AllRmReviewAPIView,
    AllHrReviewAPIView,
    AllHodReviewAPIView,
    AllCooReviewAPIView,
    AllCeoReviewAPIView,

    AppraisalStatusAPIView,
    AppraisalStatusView
)

urlpatterns = [
    path('my-appraisal-details/', MyAppraisalDetailsAPIView.as_view(), name='my-appraisal-details'),
    path('my-employee-appraisal/', MyEmployeeAppraisalAPIView.as_view(), name='my-employee-appraisal'),
    path('my-employee-appraisal/<int:pk>/', MyEmployeeAppraisalAPIView.as_view(), name='my-employee-appraisal-details'),
    path('my-rm-review/', MyRmReviewAPIView.as_view(), name='my-rm-review'),
    path('my-rm-review/<int:pk>/', MyRmReviewAPIView.as_view(), name='my-rm-review-details'),
    path('my-hr-review/', MyHrReviewAPIView.as_view(), name='my-hr-review'),
    path('my-hr-review/<int:pk>/', MyHrReviewAPIView.as_view(), name='my-hr-review-details'),
    path('my-hod-review/', MyHodReviewAPIView.as_view(), name='my-hod-review'),
    path('my-hod-review/<int:pk>/', MyHodReviewAPIView.as_view(), name='my-hod-review-details'),
    path('my-coo-review/', MyCooReviewAPIView.as_view(), name='my-coo-review'),
    path('my-coo-review/<int:pk>/', MyCooReviewAPIView.as_view(), name='my-coo-review-details'),
    path('my-ceo-review/', MyCeoReviewAPIView.as_view(), name='my-ceo-review'),
    path('my-ceo-review/<int:pk>/', MyCeoReviewAPIView.as_view(), name='my-ceo-review-details'),


    path('review-appraisal-list/rm-review/', RmReviewAppraisalListAPIView.as_view(), name='rm-review-list'),
    path('review-appraisal-list/hr-review/', HrReviewAppraisalListAPIView.as_view(), name='hr-review-list'),
    path('review-appraisal-list/hod-review/', HodReviewAppraisalListAPIView.as_view(), name='hod-review-list'),
    path('review-appraisal-list/coo-review/', CooReviewAppraisalListAPIView.as_view(), name='coo-review-list'),
    path('review-appraisal-list/ceo-review/', CeoReviewAppraisalListAPIView.as_view(), name='ceo-review-list'),
    path('review-appraisal-details/<str:employee>/', ReviewAppraisalDetailsAPIView.as_view(), name='review-appraisal-details'),
    path('review-employee-appraisal/', ReviewEmployeeAppraisalAPIView.as_view(), name='review-employee-appraisal'),
    path('review-employee-appraisal/<int:pk>/', ReviewEmployeeAppraisalAPIView.as_view(), name='review-employee-appraisal-details'),
    path('employee-rm-review/', EmployeeRmReviewAPIView.as_view(), name='employee-rm-review'),
    path('employee-rm-review/<int:pk>/', EmployeeRmReviewAPIView.as_view(), name='employee-rm-review-details'),
    path('employee-hr-review/', EmployeeHrReviewAPIView.as_view(), name='employee-hr-review'),
    path('employee-hr-review/<int:pk>/', EmployeeHrReviewAPIView.as_view(), name='employee-hr-review-details'),
    path('employee-hod-review/', EmployeeHodReviewAPIView.as_view(), name='employee-hod-review'),
    path('employee-hod-review/<int:pk>/', EmployeeHodReviewAPIView.as_view(), name='employee-hod-review-details'),
    path('employee-coo-review/', EmployeeCooReviewAPIView.as_view(), name='employee-coo-review'),
    path('employee-coo-review/<int:pk>/', EmployeeCooReviewAPIView.as_view(), name='employee-coo-review-details'),
    path('employee-ceo-review/', EmployeeCeoReviewAPIView.as_view(), name='employee-ceo-review'),
    path('employee-ceo-review/<int:pk>/', EmployeeCeoReviewAPIView.as_view(), name='employee-ceo-review-details'),


    path('all-appraisal-list/', AllAppraisalListAPIView.as_view(), name='all-appraisal-list'),
    path('all-appraisal-details/<str:employee>/', AllAppraisalDetailsAPIView.as_view(), name='all-appraisal-details'),
    path('all-employee-appraisal/', AllEmployeeAppraisalAPIView.as_view(), name='all-employee-appraisal'),
    path('all-employee-appraisal/<int:pk>/', AllEmployeeAppraisalAPIView.as_view(), name='all-employee-appraisal-details'),
    path('all-rm-review/', AllRmReviewAPIView.as_view(), name='all-rm-review'),
    path('all-rm-review/<int:pk>/', AllRmReviewAPIView.as_view(), name='all-rm-review-details'),
    path('all-hr-review/', AllHrReviewAPIView.as_view(), name='all-hr-review'),
    path('all-hr-review/<int:pk>/', AllHrReviewAPIView.as_view(), name='all-hr-review-details'),
    path('all-hod-review/', AllHodReviewAPIView.as_view(), name='all-hod-review'),
    path('all-hod-review/<int:pk>/', AllHodReviewAPIView.as_view(), name='all-hod-review-details'),
    path('all-coo-review/', AllCooReviewAPIView.as_view(), name='all-coo-review'),
    path('all-coo-review/<int:pk>/', AllCooReviewAPIView.as_view(), name='all-coo-review-details'),
    path('all-ceo-review/', AllCeoReviewAPIView.as_view(), name='all-ceo-review'),
    path('all-ceo-review/<int:pk>/', AllCeoReviewAPIView.as_view(), name='all-ceo-review-details'),

    path('appraisal-status-list/', AppraisalStatusAPIView.as_view(), name='appraisal-status-list'),
    path('appraisal-status/<int:pk>/', AppraisalStatusView.as_view(), name='appraisal-status'),


]
