# Generated by Django 5.2.4 on 2025-09-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='educational_certificates/')),
            ],
        ),
    ]
