# Generated by Django 5.2.6 on 2025-11-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_house', models.CharField(max_length=225)),
                ('present_road_block_sector', models.CharField(blank=True, max_length=50, null=True)),
                ('present_city_village', models.CharField(max_length=100)),
                ('present_postal_code', models.CharField(max_length=20)),
                ('permanent_house', models.CharField(max_length=225)),
                ('permanent_road_block_sector', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_city_village', models.CharField(max_length=100)),
                ('permanent_postal_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Attatchment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='employee_photos/')),
                ('signature', models.ImageField(upload_to='employee_signatures/')),
                ('national_id', models.FileField(upload_to='employee_nid_scans/')),
                ('passport', models.FileField(blank=True, null=True, upload_to='employee_passport_scans/')),
                ('employee_agreement', models.FileField(blank=True, null=True, upload_to='employee_agreements/')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('passing_year', models.IntegerField()),
                ('result', models.CharField(max_length=50)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='educational_certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('personal_email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_nid', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'PersonalDetail',
                'verbose_name_plural': 'PersonalDetails',
            },
        ),
        migrations.CreateModel(
            name='TrainingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('institution', models.CharField(max_length=255)),
                ('issue_date', models.IntegerField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='professional_certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('responsibilities', models.TextField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
