# Generated by Django 5.2.6 on 2025-09-16 07:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('joining_date', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('responsibilities', models.TextField(blank=True)),
                ('reviewed_by_rm', models.BooleanField(default=False)),
                ('reviewed_by_hr', models.BooleanField(default=False)),
                ('reviewed_by_hod', models.BooleanField(default=False)),
                ('reviewed_by_coo', models.BooleanField(default=False)),
                ('reviewed_by_ceo', models.BooleanField(default=False)),
                ('signature', models.FileField(blank=True, null=True, upload_to='media/employee_signature/')),
                ('image', models.FileField(blank=True, null=True, upload_to='employee_image/')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='system.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designation', to='system.designation')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgrade', to='system.subgrade')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_employees', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
            bases=('system.user',),
        ),
        migrations.AddField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='ProfessionalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=255)),
                ('credential_id', models.CharField(max_length=100, unique=True)),
                ('institution', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='professional_certificates/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_certificates', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='employees.employee')),
            ],
        ),
    ]
