# Generated by Django 5.2.6 on 2025-10-07 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('system', '0002_bddistrict_bloodgroup_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='permanent_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_permanent_address', to='system.bddistrict'),
        ),
        migrations.AlterField(
            model_name='address',
            name='permanent_police_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_permanent_address', to='system.bdthana'),
        ),
        migrations.AlterField(
            model_name='address',
            name='present_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_present_address', to='system.bddistrict'),
        ),
        migrations.AlterField(
            model_name='address',
            name='present_police_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_present_address', to='system.bdthana'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_education', to='system.degree'),
        ),
        migrations.AlterField(
            model_name='education',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_education', to='system.specialization'),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='blood_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_personal_details', to='system.bloodgroup'),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='emergency_contact_relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_personal_details', to='system.emergencycontactrelationship'),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_personal_details', to='system.maritalstatus'),
        ),
    ]
