# Generated by Django 5.2.6 on 2025-09-16 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingManager',
            fields=[
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='as_manager', serialize=False, to='employees.employee')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='employees.reportingmanager'),
        ),
    ]
