# Generated by Django 5.2.6 on 2025-10-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcertificate',
            name='issue_date',
            field=models.IntegerField(),
        ),
    ]
