# Generated by Django 5.2.6 on 2025-11-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='education',
            name='custom_degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
