# Generated by Django 5.2.6 on 2025-09-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'An Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
