# Generated by Django 5.2.6 on 2025-09-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='education',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='media/educational_certificates/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/employee_image/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='media/employee_signature/'),
        ),
        migrations.AlterField(
            model_name='professionalcertificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='media/professional_certificates/'),
        ),
    ]
