# Generated by Django 5.2.6 on 2025-09-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='educational_certificates/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='employee_image/'),
        ),
        migrations.AlterField(
            model_name='professionalcertificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='professional_certificates/'),
        ),
    ]
